name: Bug report
description: File a bug report
title: Describe the problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Your issue will be triaged by the team according to [this process](https://github.com/microsoft/react-native-windows/wiki/Triage-Process).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem Description
      description: Please enter a description of the issue. If you just have a question, please post on [Discussions](https://github.com/microsoft/react-native-windows/discussions).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps To Reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
  - type: textarea
    attributes:
      label: Expected Results
      description: Describe what you expected to happen.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Run the command `npx @react-native-community/cli info` in your terminal and copy the results here
      value: "npx @react-native-community/cli info"
      render: markdown