namespace RuntimeComponent1
{
    [default_interface]
    runtimeclass BlankUserControl : Windows.UI.Xaml.Controls.UserControl
    {
        BlankUserControl();
        Int32 MyProperty;

        static Windows.UI.Xaml.DependencyProperty MyPropertyProperty{ get; };
    }
}
