#include "pch.h"
#include "XamlMetadata.h"
#include "Crc32Str.h"

/*************************************************************
THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT MODIFY MANUALLY
**************************************************************/

#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Shapes.h>
#include <winrt/Windows.UI.Xaml.Documents.h>
#include <winrt/Windows.UI.Xaml.Controls.Maps.h>

void XamlMetadata::InitCreatorsMap() {

  xamlTypeCreatorMap = {
    { COMPILE_TIME_CRC32_STR("appBar"), []() { return winrt::Windows::UI::Xaml::Controls::AppBar(); } },
    { COMPILE_TIME_CRC32_STR("appBarButton"), []() { return winrt::Windows::UI::Xaml::Controls::AppBarButton(); } },
    { COMPILE_TIME_CRC32_STR("appBarElementContainer"), []() { return winrt::Windows::UI::Xaml::Controls::AppBarElementContainer(); } },
    { COMPILE_TIME_CRC32_STR("appBarSeparator"), []() { return winrt::Windows::UI::Xaml::Controls::AppBarSeparator(); } },
    { COMPILE_TIME_CRC32_STR("appBarToggleButton"), []() { return winrt::Windows::UI::Xaml::Controls::AppBarToggleButton(); } },
    { COMPILE_TIME_CRC32_STR("autoSuggestBox"), []() { return winrt::Windows::UI::Xaml::Controls::AutoSuggestBox(); } },
    { COMPILE_TIME_CRC32_STR("bitmapIcon"), []() { return winrt::Windows::UI::Xaml::Controls::BitmapIcon(); } },
    { COMPILE_TIME_CRC32_STR("border"), []() { return winrt::Windows::UI::Xaml::Controls::Border(); } },
    { COMPILE_TIME_CRC32_STR("button"), []() { return winrt::Windows::UI::Xaml::Controls::Button(); } },
    { COMPILE_TIME_CRC32_STR("calendarDatePicker"), []() { return winrt::Windows::UI::Xaml::Controls::CalendarDatePicker(); } },
    { COMPILE_TIME_CRC32_STR("calendarPanel"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::CalendarPanel(); } },
    { COMPILE_TIME_CRC32_STR("calendarView"), []() { return winrt::Windows::UI::Xaml::Controls::CalendarView(); } },
    { COMPILE_TIME_CRC32_STR("calendarViewDayItem"), []() { return winrt::Windows::UI::Xaml::Controls::CalendarViewDayItem(); } },
    { COMPILE_TIME_CRC32_STR("canvas"), []() { return winrt::Windows::UI::Xaml::Controls::Canvas(); } },
    { COMPILE_TIME_CRC32_STR("captureElement"), []() { return winrt::Windows::UI::Xaml::Controls::CaptureElement(); } },
    { COMPILE_TIME_CRC32_STR("carouselPanel"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::CarouselPanel(); } },
    { COMPILE_TIME_CRC32_STR("checkBox"), []() { return winrt::Windows::UI::Xaml::Controls::CheckBox(); } },
    { COMPILE_TIME_CRC32_STR("colorPicker"), []() { return winrt::Windows::UI::Xaml::Controls::ColorPicker(); } },
    { COMPILE_TIME_CRC32_STR("colorPickerSlider"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::ColorPickerSlider(); } },
    { COMPILE_TIME_CRC32_STR("colorSpectrum"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::ColorSpectrum(); } },
    { COMPILE_TIME_CRC32_STR("comboBox"), []() { return winrt::Windows::UI::Xaml::Controls::ComboBox(); } },
    { COMPILE_TIME_CRC32_STR("comboBoxItem"), []() { return winrt::Windows::UI::Xaml::Controls::ComboBoxItem(); } },
    { COMPILE_TIME_CRC32_STR("commandBar"), []() { return winrt::Windows::UI::Xaml::Controls::CommandBar(); } },
    { COMPILE_TIME_CRC32_STR("commandBarFlyoutCommandBar"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::CommandBarFlyoutCommandBar(); } },
    { COMPILE_TIME_CRC32_STR("commandBarOverflowPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::CommandBarOverflowPresenter(); } },
    { COMPILE_TIME_CRC32_STR("contentControl"), []() { return winrt::Windows::UI::Xaml::Controls::ContentControl(); } },
    { COMPILE_TIME_CRC32_STR("contentDialog"), []() { return winrt::Windows::UI::Xaml::Controls::ContentDialog(); } },
    { COMPILE_TIME_CRC32_STR("contentPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::ContentPresenter(); } },
    { COMPILE_TIME_CRC32_STR("datePicker"), []() { return winrt::Windows::UI::Xaml::Controls::DatePicker(); } },
    { COMPILE_TIME_CRC32_STR("dropDownButton"), []() { return winrt::Windows::UI::Xaml::Controls::DropDownButton(); } },
    { COMPILE_TIME_CRC32_STR("ellipse"), []() { return winrt::Windows::UI::Xaml::Shapes::Ellipse(); } },
    { COMPILE_TIME_CRC32_STR("flipView"), []() { return winrt::Windows::UI::Xaml::Controls::FlipView(); } },
    { COMPILE_TIME_CRC32_STR("flipViewItem"), []() { return winrt::Windows::UI::Xaml::Controls::FlipViewItem(); } },
    { COMPILE_TIME_CRC32_STR("flyoutPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::FlyoutPresenter(); } },
    { COMPILE_TIME_CRC32_STR("fontIcon"), []() { return winrt::Windows::UI::Xaml::Controls::FontIcon(); } },
    { COMPILE_TIME_CRC32_STR("frame"), []() { return winrt::Windows::UI::Xaml::Controls::Frame(); } },
    { COMPILE_TIME_CRC32_STR("glyphs"), []() { return winrt::Windows::UI::Xaml::Documents::Glyphs(); } },
    { COMPILE_TIME_CRC32_STR("grid"), []() { return winrt::Windows::UI::Xaml::Controls::Grid(); } },
    { COMPILE_TIME_CRC32_STR("gridView"), []() { return winrt::Windows::UI::Xaml::Controls::GridView(); } },
    { COMPILE_TIME_CRC32_STR("gridViewHeaderItem"), []() { return winrt::Windows::UI::Xaml::Controls::GridViewHeaderItem(); } },
    { COMPILE_TIME_CRC32_STR("gridViewItem"), []() { return winrt::Windows::UI::Xaml::Controls::GridViewItem(); } },
    { COMPILE_TIME_CRC32_STR("gridViewItemPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::GridViewItemPresenter(); } },
    { COMPILE_TIME_CRC32_STR("groupItem"), []() { return winrt::Windows::UI::Xaml::Controls::GroupItem(); } },
    { COMPILE_TIME_CRC32_STR("handwritingView"), []() { return winrt::Windows::UI::Xaml::Controls::HandwritingView(); } },
    { COMPILE_TIME_CRC32_STR("hub"), []() { return winrt::Windows::UI::Xaml::Controls::Hub(); } },
    { COMPILE_TIME_CRC32_STR("hubSection"), []() { return winrt::Windows::UI::Xaml::Controls::HubSection(); } },
    { COMPILE_TIME_CRC32_STR("hyperlinkButton"), []() { return winrt::Windows::UI::Xaml::Controls::HyperlinkButton(); } },
    { COMPILE_TIME_CRC32_STR("iconSourceElement"), []() { return winrt::Windows::UI::Xaml::Controls::IconSourceElement(); } },
    { COMPILE_TIME_CRC32_STR("image"), []() { return winrt::Windows::UI::Xaml::Controls::Image(); } },
    { COMPILE_TIME_CRC32_STR("inkCanvas"), []() { return winrt::Windows::UI::Xaml::Controls::InkCanvas(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbar"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbar(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarBallpointPenButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarBallpointPenButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarCustomPenButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarCustomPenButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarCustomToggleButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarCustomToggleButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarCustomToolButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarCustomToolButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarEraserButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarEraserButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarFlyoutItem"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarFlyoutItem(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarHighlighterButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarHighlighterButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarPencilButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarPencilButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarPenConfigurationControl"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarPenConfigurationControl(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarRulerButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarRulerButton(); } },
    { COMPILE_TIME_CRC32_STR("inkToolbarStencilButton"), []() { return winrt::Windows::UI::Xaml::Controls::InkToolbarStencilButton(); } },
    { COMPILE_TIME_CRC32_STR("itemsControl"), []() { return winrt::Windows::UI::Xaml::Controls::ItemsControl(); } },
    { COMPILE_TIME_CRC32_STR("itemsPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::ItemsPresenter(); } },
    { COMPILE_TIME_CRC32_STR("itemsStackPanel"), []() { return winrt::Windows::UI::Xaml::Controls::ItemsStackPanel(); } },
    { COMPILE_TIME_CRC32_STR("itemsWrapGrid"), []() { return winrt::Windows::UI::Xaml::Controls::ItemsWrapGrid(); } },
    { COMPILE_TIME_CRC32_STR("line"), []() { return winrt::Windows::UI::Xaml::Shapes::Line(); } },
    { COMPILE_TIME_CRC32_STR("listBox"), []() { return winrt::Windows::UI::Xaml::Controls::ListBox(); } },
    { COMPILE_TIME_CRC32_STR("listBoxItem"), []() { return winrt::Windows::UI::Xaml::Controls::ListBoxItem(); } },
    { COMPILE_TIME_CRC32_STR("listView"), []() { return winrt::Windows::UI::Xaml::Controls::ListView(); } },
    { COMPILE_TIME_CRC32_STR("listViewHeaderItem"), []() { return winrt::Windows::UI::Xaml::Controls::ListViewHeaderItem(); } },
    { COMPILE_TIME_CRC32_STR("listViewItem"), []() { return winrt::Windows::UI::Xaml::Controls::ListViewItem(); } },
    { COMPILE_TIME_CRC32_STR("listViewItemPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::ListViewItemPresenter(); } },
    { COMPILE_TIME_CRC32_STR("mapControl"), []() { return winrt::Windows::UI::Xaml::Controls::Maps::MapControl(); } },
    { COMPILE_TIME_CRC32_STR("mediaElement"), []() { return winrt::Windows::UI::Xaml::Controls::MediaElement(); } },
    { COMPILE_TIME_CRC32_STR("mediaPlayerElement"), []() { return winrt::Windows::UI::Xaml::Controls::MediaPlayerElement(); } },
    { COMPILE_TIME_CRC32_STR("mediaPlayerPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::MediaPlayerPresenter(); } },
    { COMPILE_TIME_CRC32_STR("mediaTransportControls"), []() { return winrt::Windows::UI::Xaml::Controls::MediaTransportControls(); } },
    { COMPILE_TIME_CRC32_STR("menuBar"), []() { return winrt::Windows::UI::Xaml::Controls::MenuBar(); } },
    { COMPILE_TIME_CRC32_STR("menuBarItem"), []() { return winrt::Windows::UI::Xaml::Controls::MenuBarItem(); } },
    { COMPILE_TIME_CRC32_STR("menuFlyoutItem"), []() { return winrt::Windows::UI::Xaml::Controls::MenuFlyoutItem(); } },
    { COMPILE_TIME_CRC32_STR("menuFlyoutPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::MenuFlyoutPresenter(); } },
    { COMPILE_TIME_CRC32_STR("menuFlyoutSeparator"), []() { return winrt::Windows::UI::Xaml::Controls::MenuFlyoutSeparator(); } },
    { COMPILE_TIME_CRC32_STR("menuFlyoutSubItem"), []() { return winrt::Windows::UI::Xaml::Controls::MenuFlyoutSubItem(); } },
    { COMPILE_TIME_CRC32_STR("navigationView"), []() { return winrt::Windows::UI::Xaml::Controls::NavigationView(); } },
    { COMPILE_TIME_CRC32_STR("navigationViewItem"), []() { return winrt::Windows::UI::Xaml::Controls::NavigationViewItem(); } },
    { COMPILE_TIME_CRC32_STR("navigationViewItemHeader"), []() { return winrt::Windows::UI::Xaml::Controls::NavigationViewItemHeader(); } },
    { COMPILE_TIME_CRC32_STR("navigationViewItemPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::NavigationViewItemPresenter(); } },
    { COMPILE_TIME_CRC32_STR("navigationViewItemSeparator"), []() { return winrt::Windows::UI::Xaml::Controls::NavigationViewItemSeparator(); } },
    { COMPILE_TIME_CRC32_STR("navigationViewList"), []() { return winrt::Windows::UI::Xaml::Controls::NavigationViewList(); } },
    { COMPILE_TIME_CRC32_STR("page"), []() { return winrt::Windows::UI::Xaml::Controls::Page(); } },
    { COMPILE_TIME_CRC32_STR("parallaxView"), []() { return winrt::Windows::UI::Xaml::Controls::ParallaxView(); } },
    { COMPILE_TIME_CRC32_STR("passwordBox"), []() { return winrt::Windows::UI::Xaml::Controls::PasswordBox(); } },
    { COMPILE_TIME_CRC32_STR("path"), []() { return winrt::Windows::UI::Xaml::Shapes::Path(); } },
    { COMPILE_TIME_CRC32_STR("pathIcon"), []() { return winrt::Windows::UI::Xaml::Controls::PathIcon(); } },
    { COMPILE_TIME_CRC32_STR("personPicture"), []() { return winrt::Windows::UI::Xaml::Controls::PersonPicture(); } },
    { COMPILE_TIME_CRC32_STR("pivot"), []() { return winrt::Windows::UI::Xaml::Controls::Pivot(); } },
    { COMPILE_TIME_CRC32_STR("pivotHeaderItem"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::PivotHeaderItem(); } },
    { COMPILE_TIME_CRC32_STR("pivotHeaderPanel"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::PivotHeaderPanel(); } },
    { COMPILE_TIME_CRC32_STR("pivotItem"), []() { return winrt::Windows::UI::Xaml::Controls::PivotItem(); } },
    { COMPILE_TIME_CRC32_STR("pivotPanel"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::PivotPanel(); } },
    { COMPILE_TIME_CRC32_STR("polygon"), []() { return winrt::Windows::UI::Xaml::Shapes::Polygon(); } },
    { COMPILE_TIME_CRC32_STR("polyline"), []() { return winrt::Windows::UI::Xaml::Shapes::Polyline(); } },
    { COMPILE_TIME_CRC32_STR("popup"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::Popup(); } },
    { COMPILE_TIME_CRC32_STR("progressBar"), []() { return winrt::Windows::UI::Xaml::Controls::ProgressBar(); } },
    { COMPILE_TIME_CRC32_STR("progressRing"), []() { return winrt::Windows::UI::Xaml::Controls::ProgressRing(); } },
    { COMPILE_TIME_CRC32_STR("radioButton"), []() { return winrt::Windows::UI::Xaml::Controls::RadioButton(); } },
    { COMPILE_TIME_CRC32_STR("ratingControl"), []() { return winrt::Windows::UI::Xaml::Controls::RatingControl(); } },
    { COMPILE_TIME_CRC32_STR("rectangle"), []() { return winrt::Windows::UI::Xaml::Shapes::Rectangle(); } },
    { COMPILE_TIME_CRC32_STR("refreshContainer"), []() { return winrt::Windows::UI::Xaml::Controls::RefreshContainer(); } },
    { COMPILE_TIME_CRC32_STR("refreshVisualizer"), []() { return winrt::Windows::UI::Xaml::Controls::RefreshVisualizer(); } },
    { COMPILE_TIME_CRC32_STR("relativePanel"), []() { return winrt::Windows::UI::Xaml::Controls::RelativePanel(); } },
    { COMPILE_TIME_CRC32_STR("repeatButton"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::RepeatButton(); } },
    { COMPILE_TIME_CRC32_STR("richEditBox"), []() { return winrt::Windows::UI::Xaml::Controls::RichEditBox(); } },
    { COMPILE_TIME_CRC32_STR("richTextBlock"), []() { return winrt::Windows::UI::Xaml::Controls::RichTextBlock(); } },
    { COMPILE_TIME_CRC32_STR("richTextBlockOverflow"), []() { return winrt::Windows::UI::Xaml::Controls::RichTextBlockOverflow(); } },
    { COMPILE_TIME_CRC32_STR("scrollBar"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::ScrollBar(); } },
    { COMPILE_TIME_CRC32_STR("scrollContentPresenter"), []() { return winrt::Windows::UI::Xaml::Controls::ScrollContentPresenter(); } },
    { COMPILE_TIME_CRC32_STR("scrollViewer"), []() { return winrt::Windows::UI::Xaml::Controls::ScrollViewer(); } },
    { COMPILE_TIME_CRC32_STR("searchBox"), []() { return winrt::Windows::UI::Xaml::Controls::SearchBox(); } },
    { COMPILE_TIME_CRC32_STR("semanticZoom"), []() { return winrt::Windows::UI::Xaml::Controls::SemanticZoom(); } },
    { COMPILE_TIME_CRC32_STR("settingsFlyout"), []() { return winrt::Windows::UI::Xaml::Controls::SettingsFlyout(); } },
    { COMPILE_TIME_CRC32_STR("slider"), []() { return winrt::Windows::UI::Xaml::Controls::Slider(); } },
    { COMPILE_TIME_CRC32_STR("splitButton"), []() { return winrt::Windows::UI::Xaml::Controls::SplitButton(); } },
    { COMPILE_TIME_CRC32_STR("splitView"), []() { return winrt::Windows::UI::Xaml::Controls::SplitView(); } },
    { COMPILE_TIME_CRC32_STR("stackPanel"), []() { return winrt::Windows::UI::Xaml::Controls::StackPanel(); } },
    { COMPILE_TIME_CRC32_STR("swapChainBackgroundPanel"), []() { return winrt::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel(); } },
    { COMPILE_TIME_CRC32_STR("swapChainPanel"), []() { return winrt::Windows::UI::Xaml::Controls::SwapChainPanel(); } },
    { COMPILE_TIME_CRC32_STR("swipeControl"), []() { return winrt::Windows::UI::Xaml::Controls::SwipeControl(); } },
    { COMPILE_TIME_CRC32_STR("symbolIcon"), []() { return winrt::Windows::UI::Xaml::Controls::SymbolIcon(); } },
    { COMPILE_TIME_CRC32_STR("textBlock"), []() { return winrt::Windows::UI::Xaml::Controls::TextBlock(); } },
    { COMPILE_TIME_CRC32_STR("textBox"), []() { return winrt::Windows::UI::Xaml::Controls::TextBox(); } },
    { COMPILE_TIME_CRC32_STR("thumb"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::Thumb(); } },
    { COMPILE_TIME_CRC32_STR("tickBar"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::TickBar(); } },
    { COMPILE_TIME_CRC32_STR("timePicker"), []() { return winrt::Windows::UI::Xaml::Controls::TimePicker(); } },
    { COMPILE_TIME_CRC32_STR("toggleButton"), []() { return winrt::Windows::UI::Xaml::Controls::Primitives::ToggleButton(); } },
    { COMPILE_TIME_CRC32_STR("toggleMenuFlyoutItem"), []() { return winrt::Windows::UI::Xaml::Controls::ToggleMenuFlyoutItem(); } },
    { COMPILE_TIME_CRC32_STR("toggleSplitButton"), []() { return winrt::Windows::UI::Xaml::Controls::ToggleSplitButton(); } },
    { COMPILE_TIME_CRC32_STR("toggleSwitch"), []() { return winrt::Windows::UI::Xaml::Controls::ToggleSwitch(); } },
    { COMPILE_TIME_CRC32_STR("toolTip"), []() { return winrt::Windows::UI::Xaml::Controls::ToolTip(); } },
    { COMPILE_TIME_CRC32_STR("treeView"), []() { return winrt::Windows::UI::Xaml::Controls::TreeView(); } },
    { COMPILE_TIME_CRC32_STR("treeViewItem"), []() { return winrt::Windows::UI::Xaml::Controls::TreeViewItem(); } },
    { COMPILE_TIME_CRC32_STR("treeViewList"), []() { return winrt::Windows::UI::Xaml::Controls::TreeViewList(); } },
    { COMPILE_TIME_CRC32_STR("twoPaneView"), []() { return winrt::Windows::UI::Xaml::Controls::TwoPaneView(); } },
    { COMPILE_TIME_CRC32_STR("userControl"), []() { return winrt::Windows::UI::Xaml::Controls::UserControl(); } },
    { COMPILE_TIME_CRC32_STR("variableSizedWrapGrid"), []() { return winrt::Windows::UI::Xaml::Controls::VariableSizedWrapGrid(); } },
    { COMPILE_TIME_CRC32_STR("viewbox"), []() { return winrt::Windows::UI::Xaml::Controls::Viewbox(); } },
    { COMPILE_TIME_CRC32_STR("virtualizingStackPanel"), []() { return winrt::Windows::UI::Xaml::Controls::VirtualizingStackPanel(); } },
    { COMPILE_TIME_CRC32_STR("webView"), []() { return winrt::Windows::UI::Xaml::Controls::WebView(); } },
    { COMPILE_TIME_CRC32_STR("wrapGrid"), []() { return winrt::Windows::UI::Xaml::Controls::WrapGrid(); } },
  };
}


