// Copyright (c) Microsoft Corporation. 
// Licensed under the MIT License.

namespace WinRTTurboModule
{
    [webhosthidden]
    [default_interface]
    runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider
    {
        ReactPackageProvider();
    };
}