// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codegen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TSEnums : Generator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
 foreach (var enumType in Util.enumsToGenerateConvertersFor) { 
            
            #line default
            #line hidden
            this.Write("export enum ");
            
            #line 7 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumType.GetName()));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 8 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
 foreach (var value in enumType.GetFields().Skip(1)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 9 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value.GetName()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 9 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((int)value.GetConstantValue(out System.Reflection.Metadata.ConstantTypeCode typeCode)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 10 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 13 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSEnums.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
