// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codegen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TSProps : TSPropsBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n/*************************************************************\r\nTHIS FILE WAS A" +
                    "UTOMATICALLY GENERATED, DO NOT MODIFY MANUALLY\r\nSOURCE WINMDS USED:\r\n");

foreach (var winmd in WinMDs) {

            this.Write("  - ");
            this.Write(this.ToStringHelper.ToStringWithCulture(winmd));
            this.Write("\r\n");

}

            this.Write(@"**************************************************************/

import type { ViewProps, NativeSyntheticEvent, ColorValue } from 'react-native';
import type * as Enums from './Enums';

export type Thickness = number | { left?: number, top?: number, right?: number, bottom?: number };

export type GridLength = number | '*' | 'auto' | `${number}*`;

export type CornerRadius = number | { topLeft?: number, topRight?: number, bottomLeft?: number, bottomRight?: number};

export type Point = { x: number, y: number };

export type Color = { a: number, r: number, g: number, b: number };

export type TypedEvent<TArgs> = {
  sender: any;
  args: TArgs;
}

");
 foreach (var t in Util.eventArgsTypes) { 
	var ns = Util.GetTSNamespace(t);
	if (ns != "") { 
            this.Write("export namespace Native");
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            this.Write(" {\r\n");
 } 
            this.Write("export type Native");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(t)));
            this.Write(" = {\r\n");
	foreach (var m in Util.GetEventArgsMethods(t.GetFullName())) { 
            this.Write("  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(m));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetEventArgsMethodArgs(t, m)));
            this.Write("): ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetEventArgsMethodReturnType(t, m)));
            this.Write("\r\n");
  }
	foreach (var prop in t.GetProperties().Where(p => Util.IsInstanceProperty(p))) { 
		var tsType = Util.GetTypeScriptType(prop);
		if (tsType != "any") {
	
            this.Write("  readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(prop)));
            this.Write(": ");
            this.Write(this.ToStringHelper.ToStringWithCulture(tsType));
            this.Write(";\r\n");

        } 
    }

            this.Write("}\r\n");
 if (ns != "") { 
            this.Write("}\r\n");
 } 
 } 
            this.Write("\r\n");
 var derived = Util.GetDerivedTypes(Types);
foreach (var type in Types) { 
 var ns = Util.GetTSNamespace(type);
if (ns != "") { 
            this.Write("export namespace Native");
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            this.Write(" {\r\n");
 } 
            this.Write("export interface Native");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(type)));
            this.Write("Props extends ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetBaseClassProps(type)));
            this.Write(" {\r\n");
 var typeProp = Util.GetJsTypeProperty(type, derived);
if (typeProp != "") { 
            this.Write("  type: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(typeProp));
            this.Write(";\r\n");
 }
foreach (var prop in type.GetProperties().Where(p => Util.ShouldEmitPropertyMetadata(p))) { 
            this.Write("  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(prop)));
            this.Write("?: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetTypeScriptType(prop)));
            this.Write(";\r\n");
 } 
foreach (var prop in FakeProps.Where(p => type == p.DeclaringType)) { 
            this.Write("  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(prop)));
            this.Write("?: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetTypeScriptType(prop)));
            this.Write("; // synthetic property\r\n");
 } 
foreach (var prop in SyntheticProps.Where(p => type == p.DeclaringType)) { 
            this.Write("  /**\r\n  * ");
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Comment));
            this.Write("\r\n  */\r\n  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(prop.Name)));
            this.Write("?: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetTypeScriptType(prop)));
            this.Write("; // synthetic property\r\n");
 } 
  foreach (var attachedDP in Util.AttachedProperties.Where(p => Properties.Any(sp => sp.Property == p && sp.DeclaringType == type))) {
            this.Write("  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(attachedDP)));
            this.Write("?: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetTypeScriptType(attachedDP)));
            this.Write("; // attached property\r\n");
 }
  foreach (var evt in type.GetEvents()) { 
            this.Write("  on");
            this.Write(this.ToStringHelper.ToStringWithCulture(evt.GetName()));
            this.Write("?: (event: NativeSyntheticEvent<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetEventArgsTSName(evt, "Native")));
            this.Write(">) => void;\r\n");
 } 
  foreach (var evt in SyntheticEvents.Where(e => type == e.DeclaringType)) { 
            this.Write("  on");
            this.Write(this.ToStringHelper.ToStringWithCulture(evt.Name));
            this.Write("?: (event: NativeSyntheticEvent<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetTypeScriptType(evt)));
            this.Write(">) => void;\r\n");
 } 
            this.Write("}\r\n");
 if (ns != "") { 
            this.Write("}\r\n");
 } 
 } 
            this.Write("\r\nexport type XamlControlProps =");
 var first = true; foreach (var type in Types) {
	if (Util.HasCtor(type) || !type.IsSealed) {
		if (!first) 
            this.Write(" | ");
 ;
		
		first = false;
		
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetNativePropsName(type)));
            this.Write("\r\n\t");
 }
	} 
            this.Write(";\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class TSPropsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
