// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codegen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TSTypes : TSTypesBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n/*************************************************************\r\nTHIS FILE WAS A" +
                    "UTOMATICALLY GENERATED, DO NOT MODIFY MANUALLY\r\n********************************" +
                    "******************************/\r\n\r\nimport type {\r\n    // Controls\r\n");
            
            #line 13 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 foreach (var type in Types.Where(t => Util.HasCtor(t) && Util.GetTSNamespace(t) == "")) { 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 14 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetNativePropsName(type)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 15 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    // EventArgs\r\n");
            
            #line 18 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 foreach (var type in Util.eventArgsTypes.Where(t => Util.GetTSNamespace(t) == "")) { 
            
            #line default
            #line hidden
            this.Write("    Native");
            
            #line 19 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 20 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 } 
            
            #line default
            #line hidden
            this.Write("} from \'./Props\';\r\n\r\n");
            
            #line 23 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 foreach (var ns in Types.Where(t => Util.HasCtor(t) && Util.GetTSNamespace(t) != "").Select(t => Util.GetTSNamespace(t)).Distinct()) { 
            
            #line default
            #line hidden
            this.Write("import type { Native");
            
            #line 24 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(" } from \'./Props\';\r\n");
            
            #line 25 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
import React, { ForwardRefExoticComponent, RefAttributes } from 'react';
import { NativeXamlControl } from './NativeXamlControl';
import { findNodeHandle, NativeMethods, UIManager } from 'react-native';

import type { Point, Color } from './Props';

export type { Point, Color };

");
            
            #line 35 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 
foreach (var type in Types.Where(t => Util.HasCtor(t))) { 
    var ns = Util.GetTSNamespace(type);
    var PropsTypeName = $"{Util.ToJsName(type)}Props";
    var RefTypeName = $"{Util.ToJsName(type)}Ref";
    var BaseTypeName = $"{Util.ToJsName(type)}Base";
    var NativePropsName = Util.GetNativePropsName(type);
    if (ns != "") { 
            
            #line default
            #line hidden
            this.Write("export namespace ");
            
            #line 43 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 44 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
  } 
            
            #line default
            #line hidden
            this.Write("export type ");
            
            #line 45 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropsTypeName));
            
            #line default
            #line hidden
            this.Write(" = Omit<");
            
            #line 45 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NativePropsName));
            
            #line default
            #line hidden
            this.Write(", \'type\'>;\r\nexport type ");
            
            #line 46 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RefTypeName));
            
            #line default
            #line hidden
            this.Write(" = React.Component<");
            
            #line 46 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NativePropsName));
            
            #line default
            #line hidden
            this.Write("> & Readonly<NativeMethods>;\r\n\r\n");
            
            #line 48 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 
  var commands = Util.GetCommands(type.GetFullName());
  string NativeMethodsFor = commands.Count() == 0 ? string.Empty : $" & NativeMethodsFor_{Util.ToJsName(type)}";
  string PartialNativeMethodsFor = commands.Count() == 0 ? string.Empty : $" & Partial<NativeMethodsFor_{Util.ToJsName(type)}>";

  if (NativeMethodsFor != string.Empty) {

            
            #line default
            #line hidden
            this.Write("export interface NativeMethodsFor_");
            
            #line 55 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(type)));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 56 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
    foreach (var command in commands) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 57 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Name));
            
            #line default
            #line hidden
            this.Write(": (ref: React.RefObject<");
            
            #line 57 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RefTypeName));
            
            #line default
            #line hidden
            this.Write(">, args: ");
            
            #line 57 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.TSArgTypes != null ? command.TSArgTypes : "any[]"));
            
            #line default
            #line hidden
            this.Write(") => void;\r\n");
            
            #line 58 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
    } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 60 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nconst ");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write(" : (ForwardRefExoticComponent<React.PropsWithChildren<");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropsTypeName));
            
            #line default
            #line hidden
            this.Write("> & RefAttributes<");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RefTypeName));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PartialNativeMethodsFor));
            
            #line default
            #line hidden
            this.Write(") = React.forwardRef((props: React.PropsWithChildren<");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropsTypeName));
            
            #line default
            #line hidden
            this.Write(">, ref: React.ForwardedRef<");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RefTypeName));
            
            #line default
            #line hidden
            this.Write(">) => <NativeXamlControl {...props} type=\'");
            
            #line 62 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetFullName()));
            
            #line default
            #line hidden
            this.Write("\' ref={ref} />);\r\n");
            
            #line 63 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"

    foreach (var command in commands) { 
            
            #line default
            #line hidden
            
            #line 65 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 65 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Name));
            
            #line default
            #line hidden
            this.Write(" = (ref: React.RefObject<");
            
            #line 65 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RefTypeName));
            
            #line default
            #line hidden
            this.Write(">, args: ");
            
            #line 65 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.TSArgTypes != null ? command.TSArgTypes : "any[]"));
            
            #line default
            #line hidden
            this.Write(") => {\r\n  const tag = findNodeHandle(ref.current);\r\n  UIManager.dispatchViewManag" +
                    "erCommand(tag, UIManager.getViewManagerConfig(\'XamlControl\').Commands.");
            
            #line 67 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 67 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(command.TSArgTypes != null ? "[args]" : "args"));
            
            #line default
            #line hidden
            this.Write(");\r\n};\r\n");
            
            #line 69 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
  } 
            
            #line default
            #line hidden
            this.Write("export const ");
            
            #line 70 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(type)));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 70 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseTypeName));
            
            #line default
            #line hidden
            this.Write(" as (ForwardRefExoticComponent<React.PropsWithChildren<");
            
            #line 70 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropsTypeName));
            
            #line default
            #line hidden
            this.Write("> & RefAttributes<");
            
            #line 70 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RefTypeName));
            
            #line default
            #line hidden
            this.Write(">> ");
            
            #line 70 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NativeMethodsFor));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 71 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
  if (ns != "") { 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 73 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
  } 
            
            #line default
            #line hidden
            
            #line 74 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"

} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 77 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"

foreach (var ea in Util.eventArgsTypes) {
    var ns = Util.GetTSNamespace(ea);
    if (ns != "") { 
            
            #line default
            #line hidden
            this.Write("export namespace ");
            
            #line 81 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 82 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"

    }

            
            #line default
            #line hidden
            this.Write("export type ");
            
            #line 85 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ea.GetName()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 85 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.GetEventArgsTSType(ea, "Native")));
            
            #line default
            #line hidden
            this.Write(";    // ");
            
            #line 85 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ea.GetFullName()));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 86 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
  if (ns != "") { 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 88 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"
  } 
            
            #line default
            #line hidden
            
            #line 89 "C:\Repos\react-native-xaml-mine\package\Codegen\TSTypes.tt"

} 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TSTypesBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
