// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codegen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TSTypes : Generator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import type {\r\n");
            
            #line 7 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
 foreach (var type in Types.Where(t => Util.HasCtor(t))) { 
            
            #line default
            #line hidden
            this.Write("    Native");
            
            #line 8 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write("Props,\r\n");
            
            #line 9 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
 } 
            
            #line default
            #line hidden
            this.Write("} from \'./Props\';\r\nimport React from \'react\';\r\nimport { NativeXamlControl } from " +
                    "\'./NativeXamlControl\';\r\n\r\n\r\n");
            
            #line 15 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
 foreach (var type in Types.Where(t => Util.HasCtor(t))) { 
            
            #line default
            #line hidden
            this.Write("export type ");
            
            #line 16 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write("Props = Omit<Native");
            
            #line 16 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write("Props, \'type\'>;\r\n\r\nexport const ");
            
            #line 18 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write(": React.FC<");
            
            #line 18 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write("Props> = (props: ");
            
            #line 18 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.GetName()));
            
            #line default
            #line hidden
            this.Write("Props) => {\r\n    return (\r\n        <NativeXamlControl type=\"");
            
            #line 20 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Util.ToJsName(type.GetName())));
            
            #line default
            #line hidden
            this.Write("\" {...props} />\r\n    );\r\n};\r\n");
            
            #line 23 "C:\Users\asklar\source\repos\react-native-xaml\package\Codegen\TSTypes.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
