name: Build RNX

on:
  workflow_call:
    inputs:
      vmImage:
        required: false
        default: 'windows-latest'
        type: string
      configuration:
        required: false
        default: 'Debug'
        type: string
      platform:
        required: false
        default: 'x64'
        type: string

jobs:
  package:
    name: Build RNX ${{ inputs.configuration }} ${{ inputs.platform }}
    runs-on: ${{ inputs.vmImage }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: yarn install
      run: yarn install 

    - name: build TS
      run: yarn build

    - name: build ReactNativeXaml.sln
      run: msbuild /restore /p:RestoreLockedMode=true /p:RestorePackagesConfig=true package\windows\ReactNativeXaml.sln /p:configuration=${{ inputs.configuration }} /p:platform=${{ inputs.platform }}

    - name: Upload build output
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: RNX ${{ inputs.configuration }} ${{ inputs.platform }} Build Output
        path: package\windows\${{ inputs.platform }}\${{ inputs.configuration }}\ReactNativeXaml\*.*
        if-no-files-found: error
