name: Build NPM Package

on:
  workflow_call:
    inputs:
      vmImage:
        required: false
        default: 'windows-latest'
        type: string

jobs:
  package:
    name: Build NPM Package
    runs-on: ${{ inputs.vmImage }}
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: yarn install
      run: yarn install 

    - name: build TS
      run: yarn build

    - name: npm pack
      run: npm pack
      working-directory: package

    - name: Upload npm package
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: RNX npm package
        path: package\*.tgz
        if-no-files-found: error
