name: Run CodeGen

on:
  workflow_call:
    inputs:
      vmImage:
        required: false
        default: 'windows-latest'
        type: string

jobs:
  codegen:
    name: Run CodeGen
    runs-on: ${{ inputs.vmImage }}
    steps:
    - name: setup git
      run: |
        git config --global core.autocrlf false
        git config --global core.filemode false

    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: yarn install
      run: yarn install

    - uses: nuget/setup-nuget@296fd3ccf8528660c91106efefe2364482f86d6f # v1.2.0

    - name: NuGet restore
      run: nuget restore -LockedMode package\windows\ReactNativeXaml.sln

    - name: run CodeGen
      run: yarn codegen
      working-directory: package

    - name: build TS
      run: yarn build

    - name: verify no changes from CodeGen
      shell: powershell
      run: |
        $changed = git status --porcelain=v1 package/
        $changed
        if ($changed -ne $null) { throw "CodeGen detected changes" }