name: Test CLI

on:
  workflow_call:
    inputs:
      vmImage:
        required: true
        default: windows-2022
        type: choice
        options:
          - windows-2022
          - windows-2019
      rnwSource:
        required: true
        default: Source
        type: choice
        options:
          - Source
          - NuGet
      rnwVersion:
        required: true
        default: '^0.71'
        type: string

jobs:
  testcli:
    name: New ${{ inputs.rnwVersion }} RNW App from ${{ inputs.rnwSource }}
    runs-on: ${{ inputs.vmImage }}
    steps:
    - uses: actions/checkout@v2

    - name: yarn install
      run: yarn install

    - name: build TS
      run: yarn build

    - name: yarn link
      run: yarn link
      working-directory: package

    - name: create ${{ inputs.rnwVersion }} app
      run: npx react-native init testrnx --template react-native@${{ inputs.rnwVersion }}

    - name: add Windows (RNW via ${{ inputs.rnwSource }})
      run: npx react-native-windows-init --overwrite ${{ inputs.rnwSource == 'NuGet' && '--experimentalNuGetDependency true' || '' }}
      working-directory: testrnx

    - name: link react-native-xaml
      run: yarn link react-native-xaml
      working-directory: testrnx

    - name: add react-native-xaml
      run: yarn add react-native-xaml
      working-directory: testrnx

    - name: autolink
      run: npx react-native autolink-windows --logging
      working-directory: testrnx

    - name: update WinUI package version
      run: ..\.github\workflows\SetUpAppForNuget.ps1 ${{ inputs.rnwSource == 'NuGet' && '-UseNuGet' || '' }}
      working-directory: testrnx

    - name: build app
      run: npx react-native run-windows --no-launch --no-deploy --no-packager --logging
      working-directory: testrnx
