name: Build RNX

on:
  workflow_call:
    inputs:
      vmImage:
        required: false
        default: 'windows-latest'
        type: string
      configuration:
        required: false
        default: 'Debug'
        type: string
      platform:
        required: false
        default: 'x64'
        type: string

jobs:
  package:
    name: Build RNX ${{ inputs.configuration }} ${{ inputs.platform }}
    runs-on: ${{ inputs.vmImage }}
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

    - name: yarn install
      run: yarn install 

    - name: build TS
      run: yarn build

    - name: build ReactNativeXaml.sln
      run: msbuild /restore /p:RestoreLockedMode=true /p:RestorePackagesConfig=true package\windows\ReactNativeXaml.sln /p:configuration=${{ inputs.configuration }} /p:platform=${{ inputs.platform }}

    - name: Upload build output
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: RNX ${{ inputs.configuration }} ${{ inputs.platform }} Build Output
        path: package\windows\${{ inputs.platform }}\${{ inputs.configuration }}\ReactNativeXaml\*.*
        if-no-files-found: error
